### ISSUE TITLE
When building up explanation at the beginning, should all sequences animate in every time? 

### ISSUE THREAD

**Issue by ProQuestionAsker** [the-pudding/infinite-web#2]
For example, Step 1 just shows the piano. Step 2 introduces the first attempt at playing the tune. 

Step 3 text says "here are the next x attempts". Should Step 3 only animate in attempts 2 - x ? Or should attempt 1 be replayed? Should attempt 1 even be displayed? 

Similarly, Step 4 says "And finally on the Y attempt, success!" So should attempts 1 - Y be animated? Or shown at all? Or should we *only* be showing step Y?

**Comment by russellgoldenberg** [comment]
each subsequent graphic should start with the previous attempts already rendered. 

step 3 starts with 1 attempt in the heatmap. 
step 4 starts with X attempts in heatmap and just plays the last one.
