### ISSUE TITLE
How do we want to distribute the guided notes? 

### ISSUE THREAD

**Issue by ProQuestionAsker** [the-pudding/infinite-web#3]
Our current rendition has them evenly spaced, which makes comparisons between attempts simpler but isn't really musically-accurate.
<img width="695" alt="Screen Shot 2020-03-18 at 2 31 23 PM" src="https://user-images.githubusercontent.com/11020849/77009496-42952b00-6925-11ea-9ad0-7b7e6739a209.png">

We could alternatively stagger them to be more musically accurate, but we may run into the following issue: 
![Group 12](https://user-images.githubusercontent.com/11020849/77010088-59884d00-6926-11ea-914d-785ab12598c5.png)
Essentially, in the sequence still overlaid with the guides, the 3rd note and duration were correct, but the full opacity block lands outside of the guides because the two notes it played previously were longer than they needed to be. Does this make understanding how to read these graphics more difficult?

**Comment by russellgoldenberg** [comment]
lets keep it with the current (first) implementation.
